use std::{
    collections::HashMap,
    fmt,
    sync::{Arc, Mutex, MutexGuard, Weak},
};

use tokio_util::sync::CancellationToken;
use uuid::Uuid;

/// Registry for transient Rust workers that can be cancelled by worker ID.
#[derive(Clone, Default)]
pub struct WorkerCancellationRegistry {
    inner: Arc<RegistryInner>,
}

/// Registration guard owned by a running worker for its entire lifetime.
pub struct WorkerRegistration {
    worker_id: WorkerId,
    cancellation: WorkerCancellation,
    registry: Weak<RegistryInner>,
}

/// Cooperative cancellation signal observed by a Rust worker.
#[derive(Clone)]
pub struct WorkerCancellation {
    token: CancellationToken,
}

/// Opaque identifier generated by Rust for one transient worker.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct WorkerId(Uuid);

/// Successful result of requesting cancellation for a known worker.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CancelWorkerOutcome {
    CancellationRequested,
    AlreadyEnded,
}

/// Bounded registry failures returned to trusted command mapping code.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WorkerCancellationError {
    WorkerNotFound,
    RegistryUnavailable,
}

/// Failure to parse a frontend-provided worker identifier.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InvalidWorkerId;

#[derive(Default)]
struct RegistryInner {
    entries: Mutex<HashMap<WorkerId, WorkerEntry>>,
}

enum WorkerEntry {
    Active(CancellationToken),
    Ended,
}

impl WorkerCancellationRegistry {
    /// Creates an empty process-local cancellation registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a new worker and returns the guard it must retain until exit.
    pub fn register(&self) -> Result<WorkerRegistration, WorkerCancellationError> {
        let cancellation = WorkerCancellation::new();
        let mut entries = self.lock_entries()?;
        let worker_id = unused_worker_id(&entries);
        entries.insert(worker_id, WorkerEntry::Active(cancellation.token.clone()));

        Ok(WorkerRegistration {
            worker_id,
            cancellation,
            registry: Arc::downgrade(&self.inner),
        })
    }

    /// Requests cancellation or reports that the known worker already ended.
    pub fn cancel(
        &self,
        worker_id: WorkerId,
    ) -> Result<CancelWorkerOutcome, WorkerCancellationError> {
        let entries = self.lock_entries()?;
        let cancellation = cancellation_for(&entries, worker_id)?;
        drop(entries);

        match cancellation {
            Some(token) => {
                token.cancel();
                Ok(CancelWorkerOutcome::CancellationRequested)
            }
            None => Ok(CancelWorkerOutcome::AlreadyEnded),
        }
    }

    fn lock_entries(
        &self,
    ) -> Result<MutexGuard<'_, HashMap<WorkerId, WorkerEntry>>, WorkerCancellationError> {
        self.inner
            .entries
            .lock()
            .map_err(|_| WorkerCancellationError::RegistryUnavailable)
    }
}

impl WorkerRegistration {
    /// Returns the Rust-generated identifier exposed by a start command.
    pub fn worker_id(&self) -> WorkerId {
        self.worker_id
    }

    /// Returns the cancellation signal the running worker must observe.
    pub fn cancellation(&self) -> WorkerCancellation {
        self.cancellation.clone()
    }
}

impl Drop for WorkerRegistration {
    fn drop(&mut self) {
        let Some(registry) = self.registry.upgrade() else {
            return;
        };

        mark_worker_ended(&registry, self.worker_id);
    }
}

impl WorkerCancellation {
    fn new() -> Self {
        Self {
            token: CancellationToken::new(),
        }
    }

    /// Resolves when cancellation is requested or the registry shuts down.
    pub async fn cancelled(&self) {
        self.token.cancelled().await;
    }

    /// Reports whether cancellation has already been requested.
    pub fn is_cancelled(&self) -> bool {
        self.token.is_cancelled()
    }
}

impl WorkerId {
    /// Parses the canonical UUID returned by a Rust worker start command.
    pub fn parse(value: &str) -> Result<Self, InvalidWorkerId> {
        Uuid::parse_str(value)
            .map(Self)
            .map_err(|_| InvalidWorkerId)
    }
}

impl fmt::Display for WorkerId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl Drop for RegistryInner {
    fn drop(&mut self) {
        let entries = self
            .entries
            .get_mut()
            .unwrap_or_else(std::sync::PoisonError::into_inner);

        for entry in entries.values() {
            if let WorkerEntry::Active(token) = entry {
                token.cancel();
            }
        }
    }
}

fn unused_worker_id(entries: &HashMap<WorkerId, WorkerEntry>) -> WorkerId {
    loop {
        let worker_id = WorkerId(Uuid::new_v4());
        if !entries.contains_key(&worker_id) {
            return worker_id;
        }
    }
}

fn cancellation_for(
    entries: &HashMap<WorkerId, WorkerEntry>,
    worker_id: WorkerId,
) -> Result<Option<CancellationToken>, WorkerCancellationError> {
    match entries.get(&worker_id) {
        Some(WorkerEntry::Active(token)) => Ok(Some(token.clone())),
        Some(WorkerEntry::Ended) => Ok(None),
        None => Err(WorkerCancellationError::WorkerNotFound),
    }
}

fn mark_worker_ended(registry: &RegistryInner, worker_id: WorkerId) {
    let Ok(mut entries) = registry.entries.lock() else {
        return;
    };

    if entries.contains_key(&worker_id) {
        entries.insert(worker_id, WorkerEntry::Ended);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dropping_registration_records_terminal_state() {
        let registry = WorkerCancellationRegistry::new();
        let registration = registry.register().expect("worker should register");
        let worker_id = registration.worker_id();

        drop(registration);

        assert_eq!(
            registry.cancel(worker_id),
            Ok(CancelWorkerOutcome::AlreadyEnded),
        );
    }

    #[test]
    fn dropping_registry_cancels_active_workers() {
        let registry = WorkerCancellationRegistry::new();
        let registration = registry.register().expect("worker should register");
        let cancellation = registration.cancellation();

        drop(registry);

        assert!(cancellation.is_cancelled());
    }
}
